# Generated by Django 4.1.3 on 2022-12-06 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.TextField(default='sem descrição', max_length=2000, verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='título')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
                ('codigo_isbn', models.CharField(max_length=13, unique=True, verbose_name='código ISBN')),
                ('descricao', models.TextField(default='sem descrição', max_length=2000, verbose_name='descrição')),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca')),
            ],
        ),
    ]
